project:
  type: website

website:
  repo-url: "https://github.com/eu-cdse/documentation"
  repo-branch: "publish"
  site-url: "https://worldcereal.github.io/"
  site-path: '/index.html'
  search:
    location: sidebar
    type: textbox
    copy-button: true

  navbar:
    background: "#F1B821"
    height: 50
    foreground: "light"
    logo-href: 'https://esa-worldcereal.org/'
    pinned: true


  page-navigation: true

  title: "WorldCereal Documentation"


  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - href: index.md
        text: Welcome
      - section: "System design"
        contents:
          - href: design/reference_data_module.ipynb
            text: Reference Data Module
          - href: design/extractions.qmd
            text: Extractions
          - href: design/inference.ipynb
            text: Inference


format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full

