project:
  type: website

bibliography: references.bib

website:
  repo-url: "https://github.com/eu-cdse/documentation"
  repo-branch: "publish"
  site-url: "https://worldcereal.github.io/"
  site-path: '/index.html'
  search:
    location: sidebar
    type: textbox
    copy-button: true

  navbar:
    background: "#F1B821"
    height: 50
    foreground: "light"
    logo-href: 'https://esa-worldcereal.org/'
    pinned: true


  page-navigation: true

  title: "WorldCereal Documentation"


  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - href: index.md
        text: Welcome
      - section: "Usage"
        contents:
          - href: usage/processing_api.md
            text: Processing API


format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full

