project:
  type: website

bibliography: references.bib

website:
  repo-url: "https://github.com/eu-cdse/documentation"
  repo-branch: "publish"
  site-url: "https://worldcereal.github.io/"
  site-path: '/index.html'
  search:
    location: sidebar
    type: textbox
    copy-button: true

  navbar:
    background: "#F1B821"
    height: 50
    foreground: "light"
    logo-href: 'https://esa-worldcereal.org/'
    pinned: true


  page-navigation: true

  title: "WorldCereal Documentation"


  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - href: index.md
        text: Welcome

      - section: "Introduction"
        contents:
          - href: intro/how_started.md
            text: How it all started
          - href: intro/purpose_scope.md
            text: Purpose and Scope
          - href: intro/system_overview.md
            text: System Overview
   
      - section: "Reference Data Module (RDM)"
        contents:
          - href: rdm/overview.md
            text: Overview
          - href: rdm/refdata.md
            text: Reference Data Harmonization
          - href: rdm/explore.md
            text: Explore and Retrieve Data
          - href: rdm/upload.md
            text: Upload Your Data
          - href: rdm/publish.md
            text: Publish Your Data

      - section: "Processing Module (PM)"
        contents:
          - href: processing/overview.md
            text: Overview
          - href: processing/supported.md
            text: Currently Supported Features
          - href: processing/planned.md
            text: Planned Features and Upgrades
          - href: processing/usage_cloud.md
            text: Usage of the Cloud System
          - href: processing/usage_standalone.md
            text: Usage of the Standalone System
      
      - section: "Visualization and Dissemination Module (VDM)"
        contents:
          - href: vdm/overview.md
            text: Overview
          - href: vdm/visualize.md
            text: Visualizing Global Products
          - href: vdm/launch.md
            text: Launch Processing Jobs
      
      - href: support.md
        text: Support and Resources     


format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full

